services:
  # O Blueprint agora cuida APENAS da API
  - type: web
    name: minha-api-prontuario
    env: docker
    envVars:
      - key: ConnectionStrings__DefaultConnection
        # A senha virá de uma variável de ambiente que criaremos manualmente
        value: "Server=sql-server;Database=ProntuarioDB;User Id=sa;Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=True"