services:
  # Serviço da sua API (usa o Dockerfile do seu repositório)
  - type: web
    name: minha-api-prontuario
    env: docker # Esta linha está CORRETA aqui, pois ele usa seu Dockerfile
    startCommand: "while ! nc -z sql-server 1433; do sleep 1; done & dotnet PostoUNICEUB.dll"
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Server=sql-server;Database=ProntuarioDB;User Id=sa;Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=True"

  # Serviço do seu Banco de Dados SQL Server (usa uma imagem pronta da internet)
  - type: pserv
    name: sql-server
    # NÃO HÁ "env: docker" AQUI. Em vez disso, usamos o bloco "image" abaixo:
    image:
      url: mcr.microsoft.com/mssql/server:2022-latest
    disk:
      name: sql-server-data
      mountPath: /var/opt/mssql
      sizeGB: 5
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: SQL_SERVER_SA_PASSWORD
        generateValue: true
      - key: MSSQL_PID
        value: "Developer"