// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostoCeub.Data.Entities;

#nullable disable

namespace PostoUNICEUB.Data.Migrations
{
    [DbContext(typeof(PostoCeubDbContext))]
    [Migration("20240927202918_Tabelas")]
    partial class Tabelas : TabelasBase
    {
    }
}
