// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PostoCeub.Data.Entities;

namespace PostoUNICEUB.Data.Migrations
{
    [DbContext(typeof(PostoCeubDbContext)), Migration("20240927202918_Tabelas")]
    internal class TabelasBase : TabelasBaseBase
    {
    }
}